fix(core): fix custom color for circlepacks
carbon-design-system/carbon-charts pull request #1033
Opened 2021-05-26 14:57 UTC by natashadecoste

### Updates
- added a demo for circle pack custom color

### Demo screenshot or recording
![image](https://user-images.githubusercontent.com/14351335/119682064-95635000-be10-11eb-872e-a2e169fa498b.png)
![image](https://user-images.githubusercontent.com/14351335/119682097-9c8a5e00-be10-11eb-834d-e2103663156d.png)

### Review checklist (for reviewers only)
- [ ] Demos all features
- [ ] Documented/annotated
- [ ] Matches UI/UX specs
- [ ] Meets the [code style guide](https://github.com/carbon-design-system/carbon-charts/wiki/Code-style-guide)
- [ ] Accessible
- [ ] Mobile first (responsive)
- [ ] RTL support (bidirectional text)
- [ ] Performant (limited bloat)

2021-05-26 16:14 UTC, theiliad requested changes

2021-05-26 16:14 UTC, theiliad commented on packages/core/src/components/graphs/circle-pack.ts
> +			.style('stroke', 'white');
hardcode to white? is this right?

2021-05-27 17:13 UTC, theiliad approved these changes

2021-06-04 18:34 UTC, cal-smith reviewed
![image](https://user-images.githubusercontent.com/1744185/120847634-c266df80-c541-11eb-843f-c428ab8692c8.png)

I get an error in Firefox when I try to load the storybook, Chrome loads fine. Latest dev edition (89.0b15 as of writing)

2021-06-04 18:47 UTC, theiliad commented
> ![image](https://user-images.githubusercontent.com/1744185/120847634-c266df80-c541-11eb-843f-c428ab8692c8.png)
> 
> I get an error in Firefox when I try to load the story for circlepack, Chrome loads fine. Latest dev edition (90.0b3 as of writing)

@natashadecoste could you pls fix this and request reviews again?

2021-06-24 19:56 UTC, theiliad approved these changes

2021-06-24 20:37 UTC, merged