feat(core): optimized asynchronous handling of graph transitions
carbon-design-system/carbon-charts pull request #1141
Opened 2021-09-09 20:57 UTC by theiliad

2021-09-09 23:09 UTC, Akshat55 commented on packages/core/src/components/component.ts
> +import { select, Selection } from 'd3-selection';
Selection interface is imported, but not used?

2021-09-10 03:49 UTC, Akshat55 requested changes

2021-09-10 03:49 UTC, Akshat55 commented on packages/core/src/components/graphs/bar-grouped.ts
>  		const { groupMapsTo } = this.getOptions().data;
Destructuring should be inside if condition

2021-09-10 03:49 UTC, Akshat55 commented on packages/core/src/components/graphs/bar-simple.ts
>  		const { groupMapsTo } = this.getOptions().data;
inside condition

2021-09-10 03:49 UTC, Akshat55 commented on packages/core/src/components/graphs/bar-stacked.ts
>  		const { groupMapsTo } = this.model.getOptions().data;
Line 173 - 175 should be  nested within the if condition similar to area and area-stacked

2021-09-17 18:45 UTC, Akshat55 approved these changes

2021-09-20 13:28 UTC, Akshat55 requested changes

2021-09-20 13:28 UTC, Akshat55 commented on packages/core/src/components/graphs/wordcloud.ts
> +
Add a destroy function and call it here, seems like even after destroy is added the function is never called. 
```suggestion
this.destory();
```

In the destroy function set all (click, mouseover, mouseout) event listeners to null 

```suggestion
	destroy() {
		this.parent.selectAll('text.word')
			.on('mouseover', null)
			.on('mousemove', null)
			.on('click', null)
			.on('mouseout', null);
	}
```

2021-09-20 13:28 UTC, Akshat55 commented on packages/core/src/components/graphs/wordcloud.ts
> +				});
Class updating is being removed (By setting to false) from the element n number of times (In demo example, 42).

Switch approach to async/await or promises.

```suggestion
				.end();
				
				//Assign merged text to promise
				promise.then(() => {
				  // Give users the option to hover and select legend after everything loads
				  self.addEventListeners(mergedText);
				  self.componentContainer.classed('updating', false); 
				});
```

2021-09-27 21:41 UTC, theiliad commented
Closed by #1169

2021-09-27 21:41 UTC, closed without merging