@Akshat55 fix(core): allow users to define custom buttons in toolbar
carbon-design-system/carbon-charts pull request #1158
Opened 2021-09-20 13:10 UTC by Akshat55

### Updates
- Fixed typo (‘hight’)
- Allow users to add ‘custom’ icons along with height & width
- Improve keyboard events (Arrow keys & selection with both spacebar and enter)
- Emit events on button click including preconfigured buttons
- Allow users to pass in a clickFunction if they don’t want to
- Assign a custom ID to the button if the user doesn't pass it in
- **If button.length is less than number of icons and user doesn't pass in the svg element content, the icon will be placed in the overflow menu including all of the succeeding buttons.**

### Demo screenshot or recording
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/38994122/134007092-bb3e8bec-5138-44c6-ab7c-b716d7b229df.png">

### Review checklist (for reviewers only)
- [ ] Demos all features
- [ ] Documented/annotated
- [ ] Matches UI/UX specs
- [ ] Meets the [code style guide](https://github.com/carbon-design-system/carbon-charts/wiki/Code-style-guide)
- [ ] Accessible
- [ ] Mobile first (responsive)
- [ ] RTL support (bidirectional text)
- [ ] Performant (limited bloat)

2021-12-08 18:57 UTC, theiliad requested changes

2021-12-08 18:57 UTC, theiliad commented on packages/core/src/components/axes/toolbar.ts
> +				d.shouldBeDisabled ? d.shouldBeDisabled() : false
Looks like lower in the code we're setting a default for `d.shouldBeDisabled`, right? Then do we need the check?

2021-12-08 18:57 UTC, theiliad commented on packages/core/src/components/axes/toolbar.ts
> +						}
I think I saw this same piece of logic 4 times, can we re-use it?

2021-12-08 18:57 UTC, theiliad commented on packages/core/src/components/axes/toolbar.ts
> +					control.id = `toolbar-button-${Toolbar.buttonID}`;
```suggestion
					control.id = `toolbar-button-${Toolbar.buttonID++}`;
```

2021-12-08 18:57 UTC, theiliad commented on packages/core/src/components/axes/toolbar.ts
> +					Toolbar.buttonID++;
```suggestion
```

2021-12-08 18:57 UTC, theiliad commented on packages/core/src/components/axes/toolbar.ts
> +					Toolbar.buttonID++;
why not do the above?

2021-12-08 18:57 UTC, theiliad commented on packages/core/src/components/axes/toolbar.ts
> +						displayIcons = false;
hmmm... why do this? why wouldn't we just move anything we find with no icons into the overflow menu?

2021-12-08 18:57 UTC, theiliad commented on packages/core/src/components/axes/toolbar.ts
> +						displayIcons = false;
this seems like an undocumented or unexpected side-effect

2021-12-08 18:57 UTC, theiliad commented on packages/core/src/components/axes/toolbar.ts
> +		// Ensures exports are always at the bottom
```suggestion
		// Ensures the `export` controls are always at the bottom
```

2021-12-13 19:34 UTC, theiliad approved these changes

2021-12-13 19:35 UTC, merged

2022-05-12 10:12 UTC, Likith-Chintala commented
what did you code bro @theiliad it never works