docs(core): add floating line combo chart example in storybook
carbon-design-system/carbon-charts pull request #1245
Opened 2021-12-15 06:56 UTC by Akshat55

### Updates
- Add documentation on using floating bar simple with combobox

fix #1215

### Demo screenshot or recording
<img width="724" alt="image" src="https://user-images.githubusercontent.com/38994122/146138157-1cb6ee40-559d-403c-8786-e335482c87da.png">

### Review checklist (for reviewers only)
- [ ] Demos all features
- [ ] Documented/annotated
- [ ] Matches UI/UX specs
- [ ] Meets the [code style guide](https://github.com/carbon-design-system/carbon-charts/wiki/Code-style-guide)
- [ ] Accessible
- [ ] Mobile first (responsive)
- [ ] RTL support (bidirectional text)
- [ ] Performant (limited bloat)

2021-12-15 20:47 UTC, theiliad requested changes
the tooltip should probably say `75 - 83`

ideas?

![image](https://user-images.githubusercontent.com/14989804/146262634-86bfb37c-c35a-4af7-bd7b-2d1471eadd64.png)

2021-12-16 04:00 UTC, Akshat55 commented
> the tooltip should probably say `75 - 83`
> 
> ideas?
> 
> ![image](https://user-images.githubusercontent.com/14989804/146262634-86bfb37c-c35a-4af7-bd7b-2d1471eadd64.png)

@theiliad 
Yea you're right, it better represents a range. Want me to make that change in this PR or another?

2021-12-16 05:12 UTC, theiliad commented
> Yea you're right, it better represents a range. Want me to make that change in this PR or another? 

Let's do it here since it's a small PR

2022-01-13 18:20 UTC, theiliad approved these changes

2022-01-13 18:21 UTC, merged