feat(core): bar group time series
carbon-design-system/carbon-charts pull request #1398
Opened 2022-06-21 20:15 UTC by cmarcink

Extends existing grouped bar support to time series scales. This should address
https://github.com/carbon-design-system/carbon-charts/issues/1396 and
https://github.com/carbon-design-system/carbon-charts/issues/1373

fix #1396, #1373

### Updates
- Grouped bar can now support ```scaleType: 'time'```

### Demo screenshot or recording
[storybook-sm.mov.zip](https://github.com/carbon-design-system/carbon-charts/files/8952483/storybook-sm.mov.zip)

### Review checklist (for reviewers only)
- [ ] Demos all features
- [ ] Documented/annotated
- [ ] Matches UI/UX specs
- [ ] Meets the [code style guide](https://github.com/carbon-design-system/carbon-charts/wiki/Code-style-guide)
- [ ] Accessible
- [ ] Mobile first (responsive)
- [ ] RTL support (bidirectional text)
- [ ] Performant (limited bloat)

2022-06-23 18:05 UTC, Akshat55 requested changes

2022-06-23 18:05 UTC, Akshat55 commented on packages/core/src/components/graphs/bar-grouped.ts
> +		let step = 70;
Should add a comment for what step is & why it is initialized to 70.

Considering `70` is also referenced in line 350, you can even create a readonly variable and assign it to step 🤔. Thoughts @theiliad on using `readonly` modifiers? It isn't used anywhere in the project

2022-06-23 18:05 UTC, Akshat55 commented on packages/core/src/components/graphs/bar-grouped.ts
> +		let step = 70;
Other than adding a comment, LGTM!

2022-06-24 17:44 UTC, Akshat55 approved these changes

2022-06-28 18:46 UTC, theiliad approved these changes
LGTM

2022-06-28 18:48 UTC, merged