Support for Vue 3
carbon-design-system/carbon-charts pull request #1593
Opened 2023-06-27 13:56 UTC by nstuyvesant

### Updates
- Updated packages/vue/package.json to have dist-tag of `next`
- Updated README.md to explain support is for Vue 3 and if an older version is needed, use `@carbon/charts-vue@latest`
- Maintenance bump for Storybook and tslib (within existing semver)
- Updated demo scripts to use StackBlitz EngineBlock template for Vue 3 instead of generic node (starts faster and doesn't require devDependencies)
- Converted components to use a factory based on Vue Composition API. All components are now 3 lines long.
- Updated Storybook to use Vue Composition API.

NOTE: Unable to do final testing in StackBlitz since there is no published `@carbon/charts-vue` component library for Vue 3; however, it tests out in a local Vue 3 project and in Storybook locally.

### Review checklist (for reviewers only)
- [ ] Demos all features
- [ ] Documented/annotated
- [ ] Matches UI/UX specs
- [ ] Meets the [code style guide](https://github.com/carbon-design-system/carbon-charts/wiki/Code-style-guide)
- [ ] Accessible
- [ ] Mobile first (responsive)
- [ ] RTL support (bidirectional text)
- [ ] Performant (limited bloat)

2023-06-27 14:30 UTC, theiliad requested changes

2023-06-27 14:30 UTC, theiliad commented on packages/vue/src/components/CcvChoroplethChart.ts
> +export default chartFactory<ChoroplethChartOptions>(ChoroplethChart, 'CcvChoroplethChart')
ExperimentalCcvChoroplethChart

2023-06-27 20:28 UTC, nstuyvesant commented on packages/vue/src/components/CcvChoroplethChart.ts
> +export default chartFactory<ChoroplethChartOptions>(ChoroplethChart, 'CcvChoroplethChart')
Just pushed the requested change.

2023-06-28 21:23 UTC, theiliad approved these changes
LGTM

2023-06-28 21:23 UTC, merged

2023-08-03 14:31 UTC, raizdev commented
@theiliad Im experience some issues, could take a look? https://github.com/carbon-design-system/carbon-charts/discussions/1641