fix(1599): animate should be false
carbon-design-system/carbon-charts pull request #1601
Opened 2023-06-28 21:37 UTC by nstuyvesant

### Updates
- Fixes https://github.com/carbon-design-system/carbon-charts/issues/1599 - axis is using animate which should have defaulted to false

2023-06-28 21:58 UTC, theiliad commented
@nstuyvesant I'm no longer seeing a left axis 😃 

<img width="897" alt="image" src="https://github.com/carbon-design-system/carbon-charts/assets/14989804/40ab839e-34cd-457f-be99-d01448a21ad3">

2023-06-28 23:22 UTC, theiliad commented
Hi @nstuyvesant, I'm still seeing the glitch (try navigating between stories)

2023-07-02 05:02 UTC, theiliad requested changes

2023-07-02 12:56 UTC, nstuyvesant commented on packages/core/src/demo/utils/stackblitz/vanilla-js.ts
> +    const response = await fetch('https://fonts.googleapis.com/css?family=IBM+Plex+Sans+Condensed:300,400|IBM+Plex+Sans:400,600&display=swap')
Clipboard paste issue. Will fix this right away.

2023-07-02 13:00 UTC, nstuyvesant commented on packages/core/src/demo/utils/stackblitz/vanilla-js.ts
> +    const response = await fetch('https://fonts.googleapis.com/css?family=IBM+Plex+Sans+Condensed:300,400|IBM+Plex+Sans:400,600&display=swap')
Pushed correct URL

2023-07-02 13:03 UTC, nstuyvesant commented
> Hi @nstuyvesant, I'm still seeing the glitch (try navigating between stories)

@theiliad - having trouble locating the issue with the graphs going from small to normal size. Looking over differences from 1.8.0, one at a time. As this PR fixes the StackBlitz issues and reverts a few of the render(animate) lines, perhaps merge this (assuming everything else looks OK) and do a separate PR for the sizing issue. Alternatively, you may be able to spot the issue quicker than me and correct it in this PR since you have access to my fork.

2023-07-03 15:59 UTC, theiliad approved these changes
LGTM

2023-07-03 17:08 UTC, merged