fix(charts-angular): issue 1650 - @carbon/charts-angular 1.8.1 release
carbon-design-system/carbon-charts pull request #1656
Opened 2023-08-26 19:09 UTC by nstuyvesant

## What problem does this solve?
- Fixes https://github.com/carbon-design-system/carbon-charts/issues/1650
- For version 1.8.0 of `@carbon/charts-angular`, the dependency on `@carbon/charts` was `^1.8.0`. Many changes were introduced in `1.9.0` and later that were not designed for `@carbon/charts-angular` 1.8.0. The package.json changes the version to `~1.8.0` to hold back the version of core.
- Also, the README.md has been updated to let users know about where to get support for Angular 16 and newer.

2023-08-27 16:07 UTC, theiliad requested changes
Just a tiny change

2023-08-27 16:07 UTC, theiliad commented on packages/angular/README.md
> +# Carbon Charts Angular
```suggestion
# Carbon Charts - Angular
```

2023-08-28 16:11 UTC, nstuyvesant commented
Sorry about the commit message on the last readme update. I just committed your suggestion without any editing.

2023-08-31 03:27 UTC, theiliad approved these changes
LGTM

2023-08-31 03:28 UTC, merged