fix(modal-domUtils):chartID initialization and addition of chartID in modal ARIA attributes
carbon-design-system/carbon-charts pull request #1722
Opened 2024-01-04 14:25 UTC by RiyaJethwa

### Updates
- [#1523](https://github.com/carbon-design-system/carbon-charts/issues/1523)
- `chartID` previously not getting initialized by `init()` has been fixed
- addition of `chartID` in `aria-labelledby` and `aria-describedby` attributes

### Demo screenshot or recording
<img width="1728" alt="image" src="https://github.com/carbon-design-system/carbon-charts/assets/76566868/fbc3324b-43b8-4035-9301-4e100bb1c098">

2024-01-04 14:26 UTC, RiyaJethwa commented
I have read the DCO document and I hereby sign the DCO.

2024-01-10 18:30 UTC, theiliad requested changes

2024-01-10 18:30 UTC, theiliad commented on packages/core/src/components/essentials/modal.ts
> +			.attr('aria-describedby', `${id}__modal-description`)
these just point to an ID, but you also need to set these IDs to the modal

(currently the modal IDs are set to `modal-title` & `modal-description`, so we need to add the `${id}__` in there

2024-01-10 18:30 UTC, theiliad commented on packages/core/src/components/essentials/modal.ts
> +			.attr('aria-describedby', `${id}__modal-description`)
over here

![image](https://github.com/carbon-design-system/carbon-charts/assets/14989804/865b6605-82c0-4645-a7bf-f7103e9c9435)

2024-01-11 15:49 UTC, theiliad approved these changes

2024-01-11 15:49 UTC, merged