fix(pie): distortion issues of hovered slices
carbon-design-system/carbon-charts pull request #1771
Opened 2024-02-28 15:49 UTC by markchou0225

### Updates
- Fix #1685: use debounce for mouse events
- Fix #1764: add an `isRendering` to prevent mouse events fired on rendering animation.

### Demo screenshot or recording

2024-02-29 16:39 UTC, theiliad requested changes
Hi @markchou0225,
Everything looks good in the demos, other than the delay that happens when hovering a slice now (which I believe is the 120ms delay of the debounce)

Can we fix that pls?

2024-02-29 18:17 UTC, markchou0225 commented
Thank you @theiliad,

I removed the `debounce` now as the distortion issue on leaving fullscreen can be solved by delay enough time (at least >= pie_slice_mouseout, i.e.: 100ms) for mouseout. Now the mouseout is using `_.delay` instead.

2024-03-01 16:25 UTC, theiliad approved these changes

2024-03-01 16:25 UTC, merged

2024-03-01 16:28 UTC, theiliad commented
thank you @markchou0225 🙌🏻