refactor(axis): use css-classes instead of style
carbon-design-system/carbon-charts pull request #1897
Opened 2024-09-27 09:39 UTC by max-jonas

* adds css-classes to ticks to make them more accessible from outside

### Updates

- issues #1896

2024-09-27 10:02 UTC, max-jonas commented
I have read the DCO document and I hereby sign the DCO.

2024-09-27 10:02 UTC, max-jonas commented
recheck

2024-09-27 16:29 UTC, theiliad requested changes

2024-09-27 16:29 UTC, theiliad commented on packages/core/scss/components/_axis.scss
> +			&.primary-tick-label {
```suggestion
			&.tick-label--primary {
```

2024-09-27 16:29 UTC, theiliad commented on packages/core/src/components/axes/axis.ts
> +					? 'primary-tick-label'
```suggestion
					? 'tick-label--primary'
```

2024-11-07 15:24 UTC, theiliad approved these changes

2024-11-07 15:24 UTC, merged