feat: add skeleton error states
carbon-design-system/carbon-charts pull request #727
Opened 2020-07-28 17:46 UTC by ryanomackey

### Updates
- Adds error states for components with skeletons (see #568)

### Demo screenshot or recording

![2020-07-28 12 43 41](https://user-images.githubusercontent.com/17710824/88701705-01313b00-d0d0-11ea-9289-97f05dba67ad.gif)

### Review checklist (for reviewers only)
- [ ] Demos all features
- [ ] Documented/annotated
- [ ] Matches UI/UX specs
- [ ] Meets the [code style guide](https://github.com/carbon-design-system/carbon-charts/wiki/Code-style-guide)
- [ ] Accessible
- [ ] Mobile first (responsive)
- [ ] RTL support (bidirectional text)
- [ ] Performant (limited bloat)

2020-08-04 17:27 UTC, natashadecoste commented on packages/core/src/components/graphs/skeleton.ts
> +
```suggestion
```

2020-08-05 18:17 UTC, ryanomackey commented
> when i hover on orange status icon, it turns purple 🟣

Ha. I almost hate to fix that.

2020-08-07 15:30 UTC, theiliad commented on packages/core/demo/data/bar.ts
> +			subtitle: "Lorem ipsum dolor sit."
Maybe we should use a real subtitle here to make for a better demo? e.g. `Unable to reach application servers at this time`

2020-08-07 15:30 UTC, theiliad commented on packages/core/demo/data/line.ts
> +export const lineErrorData = [];
What happens if data is provided? would it still show the error?

2020-08-07 15:31 UTC, theiliad commented on packages/core/src/components/graphs/skeleton.ts
>  	}
shouldn't the error be shown at all times regardless of whether the chart is loading or not? Errors probably won't always just be contained to the data, they could be about anything, and if you don't want an error to show you'd probably just remove it from options...?

2020-08-07 15:32 UTC, theiliad commented on packages/core/src/components/graphs/skeleton.ts
> +			.data(["!"]);
we should be using the correct `carbon-icon` here rather than an `!`

2020-08-07 15:32 UTC, theiliad commented on packages/core/src/components/graphs/skeleton.ts
> +			.attr("y", height / 2 + 18)
what does `/ 2 + 18` do?

2020-08-07 15:33 UTC, theiliad commented on packages/core/src/components/graphs/skeleton.ts
> +			.attr("x", "2.25em")
what's `2.25em`?

2020-08-07 15:33 UTC, theiliad commented on packages/core/src/components/graphs/skeleton.ts
> +					cy: height / 2 - 5,
what does `/ 2 - 5` do?

2020-08-07 19:50 UTC, theiliad commented
Also, I'm still seeing the purple hover state in the demos
![image](https://user-images.githubusercontent.com/14989804/89683018-b67ca380-d8c5-11ea-9099-fbc220b5c66f.png)

2020-08-18 16:12 UTC, theiliad commented
Tyler or Jeannie, could you please review? Do we just need to support error states here or should we support other icons & statuses for other types of messages?

2020-10-14 19:08 UTC, loganmccaul commented
@jeanservaas could you take a look at @theiliad's questions?

@ryanomackey could you respond to some of @theiliad's questions?

2020-10-15 15:08 UTC, theiliad commented
> @jeanservaas could you take a look at @theiliad's questions?
> 
> @ryanomackey could you respond to some of @theiliad's questions?

I've just msged Jeannie to review. I think overall I'd like to know if we should add support for more icons or other error styling that we might need.

Being able to also add an `action` might be useful, most use cases that I've seen want to show a button (e.g. no activities to visualize right now => `upload some activity data`)

2020-10-15 15:08 UTC, jeanservaas commented
@theiliad I would def just start with support icons here. Eventually we want to create a more comprehensive set of status icons (there's def and issue somewhere in the carbon backlog) but it hasn't moved forward yet.

2020-10-15 15:18 UTC, theiliad requested changes
Let's fix the react & angular issues and we can do a final code review 💯

2024-10-21 17:53 UTC, closed without merging