feat(core): add lollipop graph
carbon-design-system/carbon-charts pull request #820
Opened 2020-09-24 17:58 UTC by theiliad

2020-09-24 18:00 UTC, theiliad commented
Needs a design review

2020-09-24 18:06 UTC, mjabbink commented
👍

2020-09-24 19:14 UTC, cal-smith reviewed
One comment, looks good overall though 👍

2020-09-24 19:14 UTC, cal-smith commented on packages/core/src/components/graphs/lollipop.ts
> +	// getRadiusScale(selection: Selection<any, any, any, any>) {
Do we need to keep any of the commented code?

2020-10-01 16:17 UTC, DanaPaslaru commented
Hi, these are the design explorations for this chart: https://github.com/carbon-design-system/carbon-charts/issues/827

Thanks!

2020-10-01 17:23 UTC, mjabbink commented
Excellent exploration @DanaPaslaru

2020-10-15 17:36 UTC, sophiiae approved these changes

2020-11-24 20:19 UTC, cal-smith submitted a review, later dismissed

2020-11-25 21:16 UTC, natashadecoste requested changes
the only thing is that the legend hover doesnt affect the lines  (reducing the opacity)

2020-11-26 19:33 UTC, cal-smith approved these changes

2020-11-26 21:46 UTC, sophiiae submitted a review, later dismissed

2020-11-27 16:43 UTC, sophiiae approved these changes

2020-11-27 17:43 UTC, cal-smith approved these changes

2020-11-27 17:46 UTC, merged