fix: allow string dates in zoom bar configurations
carbon-design-system/carbon-charts pull request #823
Opened 2020-09-29 05:13 UTC by hlyang397

### Updates
- allow string dates in zoom bar configurations

### Demo screenshot or recording
![image](https://user-images.githubusercontent.com/59426533/94515122-77c7f180-0255-11eb-9680-8f23d7d4dfea.png)

### Review checklist (for reviewers only)
- [ ] Demos all features
- [ ] Documented/annotated
- [ ] Matches UI/UX specs
- [ ] Meets the [code style guide](https://github.com/carbon-design-system/carbon-charts/wiki/Code-style-guide)
- [ ] Accessible
- [ ] Mobile first (responsive)
- [ ] RTL support (bidirectional text)
- [ ] Performant (limited bloat)

2020-09-29 14:54 UTC, theiliad approved these changes

2020-09-29 14:57 UTC, theiliad requested changes
Something is still broken here. I'm not seeing any scatter points (the SVG group is empty)
![image](https://user-images.githubusercontent.com/14989804/94575648-7640fe00-0242-11eb-9c20-7ea47c243150.png)

and seeing this error
![image](https://user-images.githubusercontent.com/14989804/94575679-7fca6600-0242-11eb-8411-cd3d35a5c52a.png)

2020-09-30 04:16 UTC, hlyang397 commented
> Something is still broken here. I'm not seeing any scatter points (the SVG group is empty)
> ![image](https://user-images.githubusercontent.com/14989804/94575648-7640fe00-0242-11eb-9c20-7ea47c243150.png)
> 
> and seeing this error
> ![image](https://user-images.githubusercontent.com/14989804/94575679-7fca6600-0242-11eb-8411-cd3d35a5c52a.png)
@theiliad Thanks for catching this. Fixed in https://github.com/carbon-design-system/carbon-charts/pull/823/commits/44afba21c22f6e52fa10e3eb5dbcea1139f341ee.

2020-09-30 14:56 UTC, theiliad approved these changes

2020-09-30 17:03 UTC, natashadecoste approved these changes

2020-09-30 17:25 UTC, sophiiae approved these changes

2020-09-30 17:35 UTC, merged