Fix chart colors
carbon-design-system/carbon-charts pull request #862
Opened 2020-11-04 00:39 UTC by sophiiae

2020-11-04 16:05 UTC, theiliad requested changes

2020-11-04 16:05 UTC, theiliad commented on packages/core/src/components/graphs/gauge.ts
> +	render(animate: boolean = true) {
the fact that `animate` is a boolean is inferred **automatically** by typescript from the fact that you're setting it to `true`

2020-11-04 16:11 UTC, theiliad approved these changes

2020-11-04 16:12 UTC, theiliad approved these changes

2020-11-04 17:19 UTC, natashadecoste requested changes
using a custom color for guage is weird - if it has `delta` the user is no longer able to make use of applying a status color to `delta`, the user would have to provide override colors for **both** value and delta in order to see the what they want for the value (arc). But then it doesnt apply the color to the delta chevron meaning it isnt possible for users to handle this on their own.

we need to keep the functionality options for the delta arrow (optional carbon statuses) but also allow both colors to be handled by the user.

2020-11-06 15:17 UTC, theiliad commented
are we good here for a final review @sophiiae?

2020-11-06 18:53 UTC, sophiiae commented
> are we good here for a final review @sophiiae?

yes, it's ready for final review.

2020-11-06 19:15 UTC, theiliad approved these changes

2020-11-06 19:16 UTC, natashadecoste approved these changes

2020-11-06 19:17 UTC, merged