fix: allow toolbar button background to receive hover state change
carbon-design-system/carbon-charts pull request #884
Opened 2020-11-12 05:34 UTC by hlyang397

### Issue
When mouseover to toolbar button background (not the icon), the toolbar button background won't change the color.

### Updates
- allow toolbar button background color to receive hover state change
- use fill:transparent instead of fill: none

### Demo screenshot or recording
Before fix:
![before_fix](https://user-images.githubusercontent.com/59426533/98899670-fbc6f780-24ea-11eb-9e34-a91cb619c057.gif)

After fix:
![after_fix](https://user-images.githubusercontent.com/59426533/98899679-04b7c900-24eb-11eb-8f47-4c6239c98035.gif)

### Review checklist (for reviewers only)
- [ ] Demos all features
- [ ] Documented/annotated
- [ ] Matches UI/UX specs
- [ ] Meets the [code style guide](https://github.com/carbon-design-system/carbon-charts/wiki/Code-style-guide)
- [ ] Accessible
- [ ] Mobile first (responsive)
- [ ] RTL support (bidirectional text)
- [ ] Performant (limited bloat)

2020-11-12 17:54 UTC, theiliad requested changes
There's a bigger issue here, most zoombar demos are missing the toolbar

![image](https://user-images.githubusercontent.com/14989804/98977089-32e6da00-24e6-11eb-99ed-3fa461290945.png)

2020-11-13 04:14 UTC, hlyang397 commented
> There's a bigger issue here, most zoombar demos are missing the toolbar

@theiliad 

We had all these zoom bar demos before we got toolbar PR merged, so that is expected.
Do you like to enable toolbar in zoom bar demos in this PR?

2020-11-16 14:38 UTC, zvonimirfras approved these changes

2020-11-16 15:34 UTC, theiliad approved these changes

2020-11-16 15:40 UTC, merged