Dual axes tutorial
carbon-design-system/carbon-charts pull request #891
Opened 2020-11-16 21:58 UTC by natashadecoste

### Updates
- list
- out
- updates
- here (and don't forget to link the issues)

### Demo screenshot or recording

### Review checklist (for reviewers only)
- [ ] Demos all features
- [ ] Documented/annotated
- [ ] Matches UI/UX specs
- [ ] Meets the [code style guide](https://github.com/carbon-design-system/carbon-charts/wiki/Code-style-guide)
- [ ] Accessible
- [ ] Mobile first (responsive)
- [ ] RTL support (bidirectional text)
- [ ] Performant (limited bloat)

2020-11-19 16:40 UTC, theiliad requested changes

2020-11-19 16:40 UTC, theiliad commented on packages/core/stories/tutorials/combo-charts.ts
> +Combination charts **may or may not** use dual axes although it is common that they do. For more information on dual axes with **carbon-charts**, please see this tutorial ____.
`____`?

2020-11-19 16:40 UTC, theiliad commented on packages/core/stories/tutorials/combo-charts.ts
> +			datasets: ["Dataset 1"] // the datasets that we want to map with this type of chart
corresponding

2020-11-19 16:40 UTC, theiliad commented on packages/core/stories/tutorials/dual-axes.ts
> +___
?

2020-11-24 20:01 UTC, theiliad submitted a review, later dismissed

2020-12-01 18:39 UTC, theiliad approved these changes

2020-12-14 14:57 UTC, zvonimirfras requested changes

2020-12-14 14:57 UTC, zvonimirfras commented on packages/core/stories/tutorials/dual-axes.ts
> +\`correspondingDatasets\` on the non-primary (secondary) axis. If there is no \`correspondingDatasets\` set on the secondary axis, then the chart will render
```suggestion
\`correspondingDatasets\` on the non-primary (secondary) axis. If \`correspondingDatasets\` isn't set on the secondary axis, then the chart will render
```

2020-12-14 14:57 UTC, zvonimirfras commented on packages/core/stories/tutorials/dual-axes.ts
> +
```suggestion
```

2020-12-14 14:57 UTC, zvonimirfras commented on packages/core/stories/tutorials/dual-axes.ts
> +set up the horizontal axis (bottom) as the domain, and have the datasets' ranges mapped to the different vertical axes - "Temperature" on the left axis and "Products Sold" on the right.
```suggestion
set up the horizontal axis (bottom) as the domain, and have the datasets' ranges mapped to the different vertical axes - "Temperature" on the left axis and "Products sold" on the right.
```

2020-12-14 14:57 UTC, zvonimirfras commented on packages/core/stories/tutorials/dual-axes.ts
> +			"Products Sold"
```suggestion
			"Products sold"
```

2020-12-14 14:57 UTC, zvonimirfras commented on packages/core/stories/tutorials/dual-axes.ts
> +		  // the dataset "Products Sold" will map to this axis instead
```suggestion
		  // the dataset "Products sold" will map to this axis instead
```

2020-12-14 14:57 UTC, zvonimirfras commented on packages/core/stories/tutorials/dual-axes.ts
> +however it is best to be explicit when working with dual axes charts. If there is no \`main\` specified, the library
```suggestion
however it is best to be explicit when working with dual axes charts. If \`main\` is not specified, the library
```

2021-01-06 16:15 UTC, theiliad requested changes
g2g otherwise

2021-01-06 16:15 UTC, theiliad commented on packages/core/stories/tutorials/dual-axes.ts
> +If a chart is considered to be a **dual axes** chart, it means that the chart uses 2 **different** axes for visually mapping ranges for the data.
```suggestion
If a chart is considered to be a **dual axes** chart, it means that the chart uses 2 **different** axes for visually mapping [ranges](https://www.mathsisfun.com/sets/domain-range-codomain.html) for the data.
```

2021-01-06 16:15 UTC, theiliad commented on packages/core/stories/tutorials/combo-charts.ts
> +					enabled: false // disable the point on the LineChart won't affect the points in the AreaChart
```suggestion
					enabled: false // disabling the scatter points on the LineChart here won't affect the points in the AreaChart
```

2021-01-06 16:15 UTC, theiliad commented on packages/core/stories/tutorials/combo-charts.ts
> +					enabled: false // disable the point on the LineChart won't affect the points in the AreaChart
```suggestion
					enabled: false // disabling the scatter points on the LineChart here won't affect the points in the AreaChart
```

2021-01-06 19:38 UTC, cal-smith submitted a review, later dismissed

2021-01-08 16:09 UTC, theiliad approved these changes

2021-01-11 19:22 UTC, cal-smith approved these changes

2021-01-11 19:35 UTC, merged