Add area chart skeleton
carbon-design-system/carbon-charts pull request #910
Opened 2020-12-14 21:07 UTC by natashadecoste

### Updates
- add skeletons (grid skeleton) as export for area chart 

![image](https://user-images.githubusercontent.com/14351335/102135806-81113500-3e26-11eb-8fdf-e07aa7f36702.png)

### Review checklist (for reviewers only)
- [ ] Demos all features
- [ ] Documented/annotated
- [ ] Matches UI/UX specs
- [ ] Meets the [code style guide](https://github.com/carbon-design-system/carbon-charts/wiki/Code-style-guide)
- [ ] Accessible
- [ ] Mobile first (responsive)
- [ ] RTL support (bidirectional text)
- [ ] Performant (limited bloat)

2020-12-16 22:44 UTC, sophiiae approved these changes

2021-01-06 15:36 UTC, theiliad approved these changes

2021-01-06 15:38 UTC, theiliad requested changes
Are there new skeleton demos available?

I can't find any

![image](https://user-images.githubusercontent.com/14989804/103787131-39d42980-500b-11eb-81a0-1cd9f539c966.png)

2021-01-08 19:29 UTC, sophiiae approved these changes

2021-01-08 19:50 UTC, theiliad approved these changes

2021-01-08 19:51 UTC, merged