Donut defects
carbon-design-system/carbon-charts pull request #923
Opened 2021-01-07 21:33 UTC by natashadecoste

### Updates
fix #899 

### Demo screenshot or recording

### Review checklist (for reviewers only)
- [ ] Demos all features
- [ ] Documented/annotated
- [ ] Matches UI/UX specs
- [ ] Meets the [code style guide](https://github.com/carbon-design-system/carbon-charts/wiki/Code-style-guide)
- [ ] Accessible
- [ ] Mobile first (responsive)
- [ ] RTL support (bidirectional text)
- [ ] Performant (limited bloat)

2021-01-08 19:29 UTC, sophiiae approved these changes

2021-01-08 19:48 UTC, theiliad requested changes

2021-01-08 19:48 UTC, theiliad commented on packages/core/src/components/graphs/pie.ts
> +		});
```suggestion
			.filter(data => data.value > 0);
```

2021-01-08 19:48 UTC, theiliad commented on packages/core/src/components/graphs/pie.ts
> +		});
since we probably also don't want negative values

2021-01-13 21:14 UTC, theiliad approved these changes

2021-01-15 18:36 UTC, cal-smith approved these changes

2021-01-15 19:35 UTC, merged