feat(gauge): added hideSymbol property to gauge to prevent display of…
carbon-design-system/carbon-charts pull request #942
Opened 2021-01-28 20:47 UTC by theoshu

… symbol and x shift in value

fix #941

### Updates
- add hideSymbol boolean to hide the display of the gauge-value-symbol and prevent the horizontal shifting of the gauge-value-number

### Demo screenshot or recording

### Review checklist (for reviewers only)
- [ ] Demos all features
- [ ] Documented/annotated
- [ ] Matches UI/UX specs
- [ ] Meets the [code style guide](https://github.com/carbon-design-system/carbon-charts/wiki/Code-style-guide)
- [ ] Accessible
- [ ] Mobile first (responsive)
- [ ] RTL support (bidirectional text)
- [ ] Performant (limited bloat)

2021-02-03 21:41 UTC, natashadecoste requested changes
Thanks for creating the issue and this PR to fix it.
Only notes i have is that I think it would be better if you made the configuration key a bit more verbose like "showPercentageSymbol". This would make it more clear that its not the delta symbol toggle but the percentage token. 

And also, if you would extend it so that if there is **no percentage token** on the number value, there would also be **none on the delta value either** (see below). So basically the one configuration would turn on/off the percentage token for both.

![image](https://user-images.githubusercontent.com/14351335/106812904-51202a00-663e-11eb-890f-92573a1835b3.png)

2021-02-09 19:32 UTC, theoshu commented
@natashadecoste Done! I wasn't able to see the changes in the react storyboard. Is there a step I missed?

2021-02-11 17:23 UTC, theiliad requested changes

2021-02-11 17:23 UTC, theiliad commented on packages/core/src/components/graphs/gauge.ts
> +		}
this won't work if the user initially has percentages on & then turns them off

2021-02-11 17:23 UTC, theiliad commented on packages/core/src/components/graphs/gauge.ts
> +		); // Optical centering for the presence of the smaller % symbol
this won't work if the user initially has percentages on & then turns them off

2021-02-25 15:57 UTC, theoshu commented
@natashadecoste @theiliad 👋

2021-03-05 17:26 UTC, natashadecoste approved these changes

2021-03-14 15:25 UTC, sophiiae approved these changes

2021-03-15 17:10 UTC, theiliad approved these changes

2021-03-15 17:30 UTC, merged