chore(angular): whitelist carbon telemetry dependency for Angular CLI
carbon-design-system/carbon-charts pull request #943
Opened 2021-01-29 17:33 UTC by theiliad

2021-01-29 18:02 UTC, natashadecoste approved these changes

2021-01-29 19:36 UTC, cal-smith requested changes
There's several moving parts across these two PRs that I'm concerned about:
- where is the script to add the `postinstall` back to angular?
- https://github.com/carbon-design-system/carbon-charts/blob/master/scripts/clean-package-jsons.js from what I can tell this is still a factor? It's used in `deploy.sh` which is still in use.
- https://github.com/carbon-design-system/carbon-charts/blob/40d1d5982f58bdfcbf2e61fe5a12e5a3321731f4/packages/core/package.json#L19 this isn't going to work - there's several teams on Windows where this won't work. I'd suggest removing _all_ scripts from core after the build and only adding back the telemetry script.

I appreciate the eagerness to get this integrated, but it's clear this hasn't been tested at all.

2021-01-29 19:38 UTC, theiliad commented
> There's several moving parts across these two PRs that I'm concerned about:
> 
> * where is the script to add the `postinstall` back to angular?
> * https://github.com/carbon-design-system/carbon-charts/blob/master/scripts/clean-package-jsons.js from what I can tell this is still a factor? It's used in `deploy.sh` which is still in use.
> * https://github.com/carbon-design-system/carbon-charts/blob/40d1d5982f58bdfcbf2e61fe5a12e5a3321731f4/packages/core/package.json#L19
>    this isn't going to work - there's several teams on Windows where this won't work. I'd suggest removing _all_ scripts from core after the build and only adding back the telemetry script.
> 
> I appreciate the eagerness to get this integrated, but it's clear this hasn't been tested at all.

it's been tested locally, however the package.json cleaning script only runs in CI which is a good catch. Angular CLI doesn't remove the postinstall, I checked the dist

2021-02-01 15:46 UTC, cal-smith approved these changes
Looks great now :+1:

2021-02-01 15:46 UTC, cal-smith commented on scripts/add-telemetry-to-packages.js
> +const TELEMETRY_ENABLED_PACKAGES = [
This is excellent! Thanks 👍

2021-02-01 15:57 UTC, natashadecoste approved these changes

2021-02-01 15:59 UTC, merged