feat(core): add boxplot chart
carbon-design-system/carbon-charts pull request #958
Opened 2021-02-17 22:00 UTC by theiliad

![image](https://user-images.githubusercontent.com/14989804/108273457-9a45a300-7141-11eb-869b-cfd65522add8.png)

2021-02-18 18:28 UTC, vgb1993 commented
Hello guys, since you are actively developing this feature I was wondering if will support:
 + Multiple datasets. 
 + Horizontal orientation.
 + Time series.

I'd like to use this chart to display scheduled shipments for each driver.

Similar to a gantt chart: 
https://chandoo.org/img/pm/gantt-box-chart-template-download.png
https://github.com/scholtzan/d3-gantt.

Cheers!

2021-02-18 19:08 UTC, theiliad commented
> Hello guys, since you are actively developing this feature I was wondering if will support:
> 
> * Multiple datasets.
> * Horizontal orientation.
> * Time series.
> 
> I'd like to use this chart to display scheduled shipments for each driver.
> 
> Similar to a gantt chart:
> https://chandoo.org/img/pm/gantt-box-chart-template-download.png
> https://github.com/scholtzan/d3-gantt.
> 
> Cheers!

Hi, I think there are fundamental differences between what you've linked in your comments and what this PR is adding. Boxplots are usually used to show the distribution of elements in the data, what you're showing is basically a gantt chart

2021-02-19 08:45 UTC, vgb1993 commented
Yes there are diferences, gantt is a chart of its own. Still, a horizontal boxplot looks kind of simillar.

Anyway, cheers for adding horizontal support!

2021-02-22 15:22 UTC, natashadecoste requested changes
the deploys for react & angular aren't working for me (on Chrome) 🤔 

angular:
![image](https://user-images.githubusercontent.com/14351335/108728651-ca04fa00-74f7-11eb-9d16-e6bea4c0ed56.png)

react:
![image](https://user-images.githubusercontent.com/14351335/108728766-ddb06080-74f7-11eb-8535-97b6c2e2cca3.png)

2021-02-22 15:22 UTC, natashadecoste commented on packages/core/src/components/graphs/boxplot.ts
> +		const boxStrokeWidth = '1';
you don't want to put this in the non-customizable configurations?

2021-02-22 15:22 UTC, natashadecoste commented on packages/core/src/components/graphs/boxplot.ts
> +
```suggestion
```

2021-02-22 15:22 UTC, natashadecoste commented on packages/core/src/components/graphs/boxplot.ts
> +			.attr('d', (d, i) => {
```suggestion
			.attr('d', d => {
```

2021-02-22 15:22 UTC, natashadecoste commented on packages/core/src/components/graphs/boxplot.ts
> +			.attr('d', (d, i) => {
```suggestion
			.attr('d', d => {
```

2021-02-22 15:22 UTC, natashadecoste commented on packages/core/src/components/graphs/boxplot.ts
> +		const offset = gridSize / 2 - boxWidth / 2;
doesnt seem like you use this?

2021-02-22 15:22 UTC, natashadecoste commented on packages/core/src/components/graphs/boxplot.ts
> +			.attr('d', (d, i) => {
```suggestion
			.attr('d', d => {
```

2021-02-22 15:22 UTC, natashadecoste commented on packages/core/src/components/graphs/boxplot.ts
> +			.attr('d', (d, i) => {
```suggestion
			.attr('d', d => {
```

2021-02-22 15:22 UTC, natashadecoste commented on packages/core/src/components/graphs/boxplot.ts
> +			.attr('d', (d, i) => {
```suggestion
			.attr('d', d => {
```

2021-02-22 15:22 UTC, natashadecoste commented on packages/core/src/components/graphs/boxplot.ts
> +			.attr('d', (d, i) => {
```suggestion
			.attr('d', d => {
```

2021-02-22 15:22 UTC, natashadecoste commented on packages/core/src/components/graphs/boxplot.ts
> +			.attr('d', (d, i) => {
```suggestion
			.attr('d', d => {
```

2021-02-22 15:22 UTC, natashadecoste commented on packages/core/src/components/graphs/boxplot.ts
> +		const rangeIdentifier = this.services.cartesianScales.getRangeIdentifier();
doesn't seem like you use this range id

2021-02-22 15:22 UTC, natashadecoste commented on packages/core/src/components/graphs/boxplot.ts
> +			.attr('r', 4)
non-customizable config ?

2021-02-22 15:22 UTC, natashadecoste commented on packages/core/src/components/graphs/boxplot.ts
> +			.attr('fill-opacity', 0.3)
also a config?

2021-02-22 15:22 UTC, natashadecoste commented on packages/core/src/components/graphs/boxplot.ts
> +					.attr('fill-opacity', 0.5);
configuration for the opacity on hover?

2021-02-22 18:16 UTC, natashadecoste approved these changes

2021-02-22 18:31 UTC, sophiiae approved these changes

2021-02-22 18:34 UTC, merged