fix(core): rewrite the thresholds rendering logic
carbon-design-system/carbon-charts pull request #959
Opened 2021-02-19 23:41 UTC by theiliad

thresholds are causing massive performance issues, this fixes all of those that I can find

2021-02-22 15:43 UTC, sophiiae approved these changes

2021-02-22 18:31 UTC, sophiiae submitted a review, later dismissed

2021-02-23 15:36 UTC, natashadecoste requested changes
looks good 👍 just spelling change

2021-02-23 15:36 UTC, natashadecoste commented on packages/core/src/components/essentials/threshold.ts
> +			.selectAll('g.axis-tresholds')
```suggestion
			.selectAll('g.axis-thresholds')
```

2021-02-23 15:36 UTC, natashadecoste commented on packages/core/src/components/essentials/threshold.ts
> +			(d) => `axis-tresholds ${d.axisPosition}`
```suggestion
			(d) => `axis-thresholds ${d.axisPosition}`
```

2021-02-23 17:45 UTC, natashadecoste approved these changes

2021-02-23 18:45 UTC, sophiiae approved these changes

2021-02-23 18:47 UTC, merged