feat(core): add bullet graph
carbon-design-system/carbon-charts pull request #969
Opened 2021-03-10 20:05 UTC by theiliad

Questions:
- are there always going to be 3 areas max?
- what if the user doesn't provide any areas?
- are the 3 areas always called Poor, Satisfactory & Great?

2021-03-12 19:47 UTC, DianaStanciulescu commented
1. i think we should limit to 3 unless we get push against it (we run into some accessibility issues if we don;t)

2. there is an option without any area - that space is shown like a simple rectange
<img width="1014" alt="Screenshot 2021-03-12 at 21 46 57" src="https://user-images.githubusercontent.com/51086727/110990795-7e1dd600-837c-11eb-9667-97f6d5c59084.png">

3. no, they can be called whatever people need to call them.

2021-03-15 20:33 UTC, sophiiae submitted a review, later dismissed

2021-03-17 17:26 UTC, natashadecoste requested changes
the tooltip _values_ are correct, but the color flag seems to only ever use the first default purple
![image](https://user-images.githubusercontent.com/14351335/111510260-fe995980-8723-11eb-9cfb-062dc4cbb3dd.png)

2021-03-17 17:26 UTC, natashadecoste commented on packages/core/demo/data/bullet.ts
> +import { mouse } from 'd3';
```suggestion
```

2021-03-17 19:00 UTC, theiliad commented
> the tooltip _values_ are correct, but the color flag seems to only ever use the first default purple

fixed

2021-03-18 08:14 UTC, DianaStanciulescu commented
hi @theiliad , question: why are the X axis values slanted, and if the need to be, why is 0 slanted the other way?

2021-03-18 08:15 UTC, DianaStanciulescu commented
also, the quartile marks on top of the colored bar should be black in the dark theme, and white when they are outside the colored bars.

2021-03-18 19:53 UTC, cal-smith submitted a review, later dismissed

2021-03-18 19:54 UTC, cal-smith commented
Just a code review on my part 👍

2021-03-18 20:02 UTC, theiliad commented
> hi @theiliad , question: why are the X axis values slanted, and if the need to be, why is 0 slanted the other way?

the slanting is a bug in the axis charts where in some cases the labels (that do fit) are still slanted, have to fix that

2021-03-19 14:33 UTC, sophiiae approved these changes

2021-03-19 15:35 UTC, theiliad commented
Have to convert to draft again since we're missing:
1. correct legend behaviour #725 
2. wrappers

2021-03-22 20:56 UTC, mjabbink commented
@theiliad I think the inside chart background should be white when on G10 background. 

<img width="771" alt="Screen Shot 2021-03-22 at 3 52 30 PM" src="https://user-images.githubusercontent.com/32881239/112057388-32f78600-8b27-11eb-8bde-3f17fc8be92c.png">

2021-03-22 20:57 UTC, mjabbink commented
Currently all G10.

<img width="749" alt="Screen Shot 2021-03-22 at 3 52 54 PM" src="https://user-images.githubusercontent.com/32881239/112057414-3ab72a80-8b27-11eb-846a-f400a7ca594f.png">

2021-03-22 20:58 UTC, mjabbink commented
Same for dark G90 dark theme

<img width="757" alt="Screen Shot 2021-03-22 at 3 57 37 PM" src="https://user-images.githubusercontent.com/32881239/112057548-6e925000-8b27-11eb-907e-51d096370bfe.png">


<img width="753" alt="Screen Shot 2021-03-22 at 3 57 52 PM" src="https://user-images.githubusercontent.com/32881239/112057566-74883100-8b27-11eb-849b-f8c66a1e659c.png">

2021-03-22 20:58 UTC, mjabbink commented
@DianaStanciulescu  :point_up:

2021-03-22 21:05 UTC, jeanservaas commented
Agree about live chart background. I'm pretty sure this was just an oversight and not intentional as far as I can remember. 

So I'm assuming that there is still tone in those first sections, like this:
![image](https://user-images.githubusercontent.com/43144260/112058259-bc5f8600-8b30-11eb-8e82-0f3e58d88445.png)

2021-03-22 21:38 UTC, mjabbink commented
I wonder in the case of this chart it’s better as it is? Seems almost to get more busy following the suggestion?

2021-03-23 08:35 UTC, DianaStanciulescu commented
yes, the bg was not intentional, it should be indeed white. i worked on completely white BG so I missed pointing this out. 

i guess they all look busier with white bg vs g10 general bg,  but at the same time maybe more legible, better contrast, etc?

2021-03-23 14:19 UTC, mjabbink commented
And probably more typically on white or G100 but totally guessing. Also best to stay consistent. We can change if we think it will hinder readability later on down the line.

2021-04-28 14:48 UTC, sophiiae submitted a review, later dismissed

2021-04-28 15:31 UTC, sophiiae approved these changes

2021-04-28 15:40 UTC, theiliad commented
> @DianaStanciulescu ☝️ FYI @jeanservaas

I just added the BGs on g10 & g90

2021-04-28 19:25 UTC, natashadecoste submitted a review, later dismissed

2021-04-28 19:50 UTC, sophiiae approved these changes

2021-04-28 19:52 UTC, natashadecoste approved these changes

2021-04-28 20:04 UTC, merged