improvement(configuration for gridline/tick alignment)
carbon-design-system/carbon-charts pull request #977
Opened 2021-03-22 22:06 UTC by natashadecoste

### Updates
override x or y grid to correspond with tick values
it defaults to carbon specs for x and y gridlines (5 on y and 15 on x)

### Demo screenshot or recording
## current behaviour
currently if you customize the tick values for an axis, there is no way to get the gridlines to line up to the tick values
**below has a custom Y axis** 
![image](https://user-images.githubusercontent.com/14351335/112063729-3cd5b500-8b38-11eb-904b-4f61f37a786f.png)

![image](https://user-images.githubusercontent.com/14351335/112063774-4e1ec180-8b38-11eb-89fd-5d6fce789d94.png)
codesandbox: https://codesandbox.io/s/zen-water-jocd6?file=/src/index.js:772-805

## new behaviour
if there are custom tick values, the grid can use that:
![image](https://user-images.githubusercontent.com/14351335/112063979-a655c380-8b38-11eb-9950-339db2857a95.png)

##### options
```
export const simpleBarOptionsCustomTicks = {
	title: 'Simple bar (custom ticks)',
	axes: {
		left: {
			mapsTo: 'value',
			ticks: {
				values: [0, 1.2, 1.3, 2],
			},
		},
		bottom: {
			mapsTo: 'group',
			scaleType: 'labels',
		},
	},
	grid: {
		y: {
			useTickValues: true, // defaults to carbon specs for number of ticks
		}
	}
};
```

### Review checklist (for reviewers only)
- [ ] Demos all features
- [ ] Documented/annotated
- [ ] Matches UI/UX specs
- [ ] Meets the [code style guide](https://github.com/carbon-design-system/carbon-charts/wiki/Code-style-guide)
- [ ] Accessible
- [ ] Mobile first (responsive)
- [ ] RTL support (bidirectional text)
- [ ] Performant (limited bloat)

2021-03-24 14:39 UTC, theiliad requested changes

2021-03-24 14:39 UTC, theiliad commented on packages/core/src/configuration.ts
> +		useTickValues: false
would `alignWithAxisTicks` be a more intuitive name?

2021-03-29 17:33 UTC, theiliad approved these changes

2021-03-29 18:07 UTC, sophiiae approved these changes

2021-03-29 18:53 UTC, merged